;;; check-extensions.el --- Script/native extension compatibility -*- lexical-binding: t; -*-
;;; Commentary:
;; Runs the outer script pipeline, a .cfg mapping, an explicit .mk4 file,
;; a native Lua filter, and the built-in inlinecss extension together.
;;; Code:
(require 'static-site)

(let* ((package-root (file-name-directory load-file-name))
       (cache (expand-file-name ".cache/" package-root))
       (_ (make-directory cache t))
       (fixture (make-temp-file (expand-file-name "native-extensions-" cache) t))
       (emacs (expand-file-name invocation-name invocation-directory))
       (started (float-time)))
  (unwind-protect
      (with-temp-buffer
        (let ((file (expand-file-name "main.tex" fixture)))
          (with-temp-file file
            (insert "\\documentclass{article}\n"
                    "\\newcommand{\\NativeProbe}{Fallback text}\n"
                    "\\begin{document}\n\\section{Extension compatibility}\n"
                    "\\input{generated.tex}\n\\NativeProbe\n"
                    "\\[a^2+b^2=c^2\\]\n\\end{document}\n"))
          (with-temp-file (expand-file-name "generate.el" fixture)
            (insert ";;; -*- lexical-binding: t; -*-\n"
                    "(with-temp-file \"generated.tex\" (insert \"Generated by a script plugin.\\n\"))"))
          (with-temp-file (expand-file-name "web.cfg" fixture)
            (insert "\\Preamble{xhtml}\n"
                    "\\AtBeginDocument{\\renewcommand{\\NativeProbe}{\\HCode{<span id=\"extension-probe\">Native config marker</span>}}}\n"
                    "\\Css{[id='extension-probe'] {color: rgb(12,34,56);}}\n"
                    "\\begin{document}\n\\EndPreamble\n"))
          (with-temp-file (expand-file-name "build.mk4" fixture)
            (insert "local filter = require 'make4ht-filter'\n"
                    "Make:add('probe', function()\n"
                    "  local f = assert(io.open('mk4-ran.txt', 'w'))\n"
                    "  f:write('native build file ran'); f:close(); return 0\n"
                    "end, {correct_exit=0})\n"
                    "Make:probe()\nMake:htlatex()\n"
                    "Make:match('html$', filter {function(s)\n"
                    "  return (s:gsub('Generated by a script plugin', 'Native filter processed plugin content'))\n"
                    "end})\n"))
          (let ((static-site-make4ht-options
                 '("-x" "-f" "html5+inlinecss" "-c" "web.cfg" "-e" "build.mk4")))
            (static-site-make4ht-setup file))
          (setq-local static-site-generators (list (list "content" emacs "--batch" "-Q" "-l" "generate.el")))
          (let* ((state (static-site--state))
                 (log (static-site--buffer state "extension test"))
                 (deadline (+ (float-time) 120))
                 done succeeded)
            (static-site--run state (static-site--build-steps (static-site--root)) log
                              (lambda (ok) (setq done t succeeded ok)))
            (while (and (not done) (< (float-time) deadline)) (accept-process-output nil 0.1))
            (unless (and done succeeded)
              (when (buffer-live-p log) (princ (with-current-buffer log (buffer-string))))
              (static-site-cancel)
              (error "Native extension integration failed"))
            (unless (file-exists-p (expand-file-name "mk4-ran.txt" fixture))
              (error "The native build file did not execute"))
            (with-temp-buffer
              (insert-file-contents (expand-file-name "public/main.html" fixture))
              (unless (search-forward "Native filter processed plugin content" nil t)
                (error "Native filter did not transform plugin-generated content"))
              (goto-char (point-min))
              (unless (re-search-forward "<span[^>]*id=['\"]extension-probe['\"][^>]*>Native config marker</span>" nil t)
                (error "Native TeX4ht configuration output is missing"))
              (unless (string-match-p "style=['\"][^'\"]*rgb(12,34,56)" (match-string 0))
                (error "The inlinecss extension did not inline the configured CSS")))
            (message "NATIVE_EXTENSION_COMPATIBILITY_OK .cfg + .mk4 + Lua filter + inlinecss %.2fs"
                     (- (float-time) started)))))
    (when (file-in-directory-p (file-truename fixture) cache)
      (delete-directory fixture t))))

;;; check-extensions.el ends here
