;;; check-make4ht.el --- Framework-free make4ht smoke check -*- lexical-binding: t; -*-
(setq load-prefer-newer t)
(require 'static-site)

(let* ((package-root (file-name-directory load-file-name))
       (cache (expand-file-name ".cache/" package-root))
       (_ (make-directory cache t))
       (fixture (make-temp-file (expand-file-name "native-make4ht-" cache) t))
       (emacs (expand-file-name invocation-name invocation-directory))
       (started (float-time)))
  (unwind-protect
      (with-temp-buffer
        (let ((file (expand-file-name "main.tex" fixture)))
          (with-temp-file file
            (insert "\\documentclass{article}\n\\begin{document}\n"
                    "\\section{A standalone static document}\n"
                    "\\input{generated.tex}\n\\[a^2+b^2=c^2\\]\n\\end{document}\n"))
          (with-temp-file (expand-file-name "generate.el" fixture)
            (insert ";;; -*- lexical-binding: t; -*-\n"
                    "(with-temp-file \"generated.tex\" (insert \"Generated by a script plugin.\\n\"))"))
          (static-site-make4ht-setup file)
          (setq-local static-site-generators (list (list "content" emacs "--batch" "-Q" "-l" "generate.el")))
          (let* ((state (static-site--state))
                 (log (static-site--buffer state "native test"))
                 (deadline (+ (float-time) 120))
                 done succeeded)
            (static-site--run state (static-site--build-steps (static-site--root)) log
                              (lambda (ok) (setq done t succeeded ok)))
            (while (and (not done) (< (float-time) deadline)) (accept-process-output nil 0.1))
            (unless (and done succeeded)
              (when (buffer-live-p log) (princ (with-current-buffer log (buffer-string))))
              (static-site-cancel)
              (error "Standalone make4ht integration failed"))
            (let* ((source (static-site--public (static-site--root)))
                   (snapshot (static-site--snapshot (static-site--root) source)))
              (with-temp-buffer
                (insert-file-contents (expand-file-name "main.html" snapshot))
                (unless (search-forward "Generated by a script plugin" nil t)
                  (error "Plugin content missing from make4ht HTML")))
              (static-site--remove-snapshot (static-site--root) snapshot))
            (message "NATIVE_MAKE4HT_PLUGIN_AND_SNAPSHOT_OK %.2fs" (- (float-time) started)))))
    (when (file-in-directory-p (file-truename fixture) cache)
      (delete-directory fixture t))))
